---
title: "Article 6"
description: "Translucent frog optics create camo color"

author:
  - name: Shawn Lemaire
    url: {https://github.com/ShawnLemaire}
date: "`r Sys.Date()`"
preview: grenouille.png
categories:
  - "English for Science"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Source of the article and dates 
**Source** : https://www.scientificamerican.com/podcast/episode/translucent-frog-optics-create-camo-color/

**Publication date** : August 4th, 2020

**Consultation date of the article** : March 11rd, 2021

**Word count** : ??? words 

**Picture credits** : COSTA RICAN AMPHIBIAN RESEARCH CENTER via academia.edu

## Important vocabulary

| Word from the text | Synonym / definition | French translation |
|-----|-----|-----|
| / | / | / |

## Analysis table about the study

| Basic analysis subjects | Informations |
|-----|-----|
| Researchers |  |
| Published in / When ? | August 4th, 2020 |
| General topic |  |
| Procedure / What was examined | Some animals have cells in their skin which contain chromatophores but these frogs prefer to be translucent this allow to the light reflect by the substrat to go through their, which is better than a green camouflage that frogs can not change

Many marin animals have developped this technic but there only a few of terrestre metazoa that have this ability. There are several reasons that explain that.
First, the difference between the two environment which is under water on the on hand, and on the other hand which is aerian. The intercation between the tissues and the light will be modified
Indeed, the light in the seas and in the oceans always comes from above while depth are dark. In the jungle, light comes from all directions as long as we are not above canopy.

This frog is not really transparent but tranlucent cause his skin is thin enough so that the light can traverse it






|In the ocean, light is always coming from above, and the background is less variable. But in jungle canopy, light is coming from many directions, and the background is far more variable. Enter a little critter called the glass frog. It’s not actually transparent; it’s translucent. That means its skin in some places is thin enough that you can actually see its internal organs hard at work. 

“Most of the time, when you see photographs of these frogs, they’re taken under quite controlled conditions, with either strong lighting, like a powerful flash, or they’re photographed from underneath on a piece of glass, and it’s really their bellies which are transparent. And these frogs are pretty small and thin and quite delicate, so if you have a powerful flash on your camera, you can sort of just blast light through them, and they will look pretty transparent.”

Barnett says the frog’s translucent skin is actually a novel camouflage strategy that no one’s ever really studied—until now.

“What we think is happening is that light is traveling through the frog, interacting with the pigmentation. But a lot of it does pass through the frog. Some of that light will be absorbed by the background underneath the frog. But some of it will be reflected off that background and come back through the frog.”  

So if a glass frog is sitting on a bright green leaf, high in the jungle canopy, the light passing through its thin skin and onto the leaf will make the frog appear brighter in color, matching more closely with the leaf.

The jungle canopy is filled with leaves, but it’s also filled with predators: birds, snakes, mammals and even invertebrates in search of their next meal. 

“And these animals are quite—their visual systems are pretty cued in to finding differences in luminance and brightness between different patches. So they’re quite good at finding prey based on differences between the background and the animal’s brightness. And by being translucent, it seems, these frogs are able to have an adaptive camouflage.”

So regardless of whether the leaf is dark or bright, if the glass frog is sitting on it, it will appear to change to more closely match its background. The study by Barnett and colleagues is in the Proceedings of the National Academy of Sciences. [James B. Barnett el al., Imperfect transparency and camouflage in glass frogs]

With around 150 known species of glass frogs in the world, Barnett says the next project is to find out if the frogs’ translucency may differ based on their individual habitats. One thing is certain: it will be hard to see what they find.
| Remaining questions | / |











