---
title: "Two different summaries"
description: "A short description of two other scientific blogs like this one" 
author:
  - name: Shawn Lemaire
    url: {https://github.com/ShawnLemaire}
date: "`r Sys.Date()`"
categories:
  - "English for Science"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## First blog summary

### ["The notion of time" by Joachim Viseur](https://joachimviseur201163.wordpress.com/)

The notion of time is something that fascinates me, especially when I read that it is mathematically possible to travel in it and that according to some researchers, the newly created paradoxes will adjust themselves back to normal. There are 2 theories that would explain all the specificities of this notion: general relativity (the duration of a second depends on the speed of the clock, the closer we get to the speed of light the more the notion of time changes, we can even travel into the future) and mechanical quantum (the quantum superposition allows a second to have two different speeds at the same time) they are opposed but researchers agree that the universal unit of measurement of time is 1e -33 s. This can be measured with an atomic clock that works with Th 226, which emits waves whose wavelength is picked up by a laser; it will be more accurate if it is based only on the atom. Other experiments have been done such as placing two atomic clocks near a reactor and another one further away and observing the time differences that occur, thus giving a value to the quantum effect.
This is what we can learn from this blog on such an interesting subject.

