---
title: "Article 7"
description: "'Naked' shark was born without skin or teeth in world first"

author:
  - name: Shawn Lemaire
    url: {https://github.com/ShawnLemaire}
date: "`r Sys.Date()`"
preview: requin.png
categories:
  - "English for Science"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Source of the article and dates 
**Source** : https://www.livescience.com/naked-skinless-shark-mediterranean-sea.html

**Publication date** : October 2nd, 2020

**Consultation date of the article** : March 3rd, 2021

**Word count** : 313 words 

## Important vocabulary

| Word from the text | Synonym / definition | French translation |
|-----|-----|-----|
| / | / | / |

## Analysis table about the study

| Basic analysis subjects | Informations |
|-----|-----|
| Researchers |  |
| Published in / When ? | October 2nd, 2020 |
| General topic | A shark without skin or teeth was discovered for the first time in the world. It is a Galeus melastomus (or "blackmouth shark") caught by fishermen in July 2019. |
| Procedure / What was examined | We know the species because scientists have been experimenting to try and find out if it is not a new type of shark in addition to the more than 300 species already described.Scientists had previously seen sharks with albinism or other skin mutations, but none with this "severe lack of all skin-related structures, including teeth". Stranger still, the shark seemed to be living a normal life; in fact, the animal was three years old, had normal growth and was found with a full belly. It was clearly incredible. Normal Galeus melastomus are small sharks that can reach a maximum length of 70 centimetres; they live between 200 and 500 metres deep in the Northeast Atlantic and Mediterranean. True to its name, its mouth is black on the inside like the skin-like sheath that covers its internal organs. And note that this sheath can be seen through the animal. After some research, the scientists announced that it was a female and that her 30 centimetres was a normal length for her 3 years old. In addition to its epidermis, it has no dermal denticules (a tiny tooth-shaped structure on the skin of sharks and rays). These scales allow for the protection of the fish and better hydrodynamics. Despite everything, this little shark was a good hunter as we found 14 different foods in its stomach (like small cephalopods, crustaceans,...); this kind of fish eating its prey whole, the lack of teeth did not change much its ability to eat (unlike the lack of dermal teeth which makes it a worse swimmer than its peers. |
| Conclusion / Discovery | This strange appearance may be due to a mutation or exposure to chemical pollution. Scientists will analyse the water and sediment in the place where the animal was found to find out more. |
| Remaining questions | / |
