---
title: "Article 3"
description: "How Ultra-Black Fish Disappear in the Deepest Seas"
  
author:
  - name: Shawn Lemaire
    url: {https://github.com/ShawnLemaire}
date: "`r Sys.Date()`"
preview: Imagearticle3.png
categories:
  - "English for Science"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Source of the article and dates 
**Source** : https://www.nytimes.com/2020/07/16/science/ultra-black-fish.html

**Publication date** : July 16th, 2020

**Consultation date of the article** : October 23th, 2020

**Word count** : 215 words 

## Important vocabulary

| Word from the text | Synonym / definition | French translation |
|-----|-----|-----|
| 1. Melanin | Dark biological pigments, which are responsible in particular for the colouring of the teguments in the animal kingdom. | Mélanine |
| 2. Melanosome | The melanosome is an intracellular organelle within which melanins are produced. | Mélanosomes |

## Analysis table about the study

| Basic analysis subjects | Informations |
|-----|-----|
| Researchers | Alexander Davis from Duke University and Karen Osborn from the Smithsonian National Museum of Natural History |
| Published in / When ? | July 16th, 2020 |
| General topic | Some fish can be "invisible" thanks to their skin, which absorbs more than 99.9% of the light. |
| Procedure / What was examined | There are several fishes ( and a few other animals like spiders, birds,...) that are able to do this but the champion reflects less than 0.05% of the light while the black paper on the market reflects 10%. They have pigments in their skin that swallow light with very good efficiency. Most animals have melanin to appear coloured in melanosomes arranged in a single layer that reflects the light not being absorbed by it, but not ultra-black animals. In the case of fishes, it is a technique to approach their prey without being seen or to attract them with a bioluminescent lure and thus hunt easily. It may seem useless in the depths of the ocean when you know that there is no light in the middle, but there are a lot of bioluminescent animals, it is really a rainbow and it is therefore very interesting to be invisible. |
| Conclusion / Discovery | Thanks to samples on these animals, we have discover that ultra-black animals have many packets of melanosom that absorb the light and **derive** the part that has not been absorbed towards another packet of melanosomes that swallows the light again and so on. |
| Remaining questions | / |
